#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

TERRAINS="${TRACER_DATA_TERRAINS:-flat_normal rough_mid slope_5deg}"
STYLES="${TRACER_DATA_STYLES:-fast cautious high_clearance}"
REPEATS="${TRACER_DATA_REPEATS:-5}"
DURATION="${TRACER_DATA_DURATION_SEC:-20.0}"
SAMPLE_HZ="${TRACER_DATA_SAMPLE_HZ:-5.0}"
CAMPAIGN_ID="${TRACER_DATA_CAMPAIGN_ID:-objective_selector_data_v1}"

echo "[TRACER] objective selector data campaign"
echo "[TRACER] terrains=${TERRAINS}"
echo "[TRACER] styles=${STYLES}"
echo "[TRACER] repeats=${REPEATS}"
echo "[TRACER] duration=${DURATION}"
echo "[TRACER] sample_hz=${SAMPLE_HZ}"
echo "[TRACER] campaign_id=${CAMPAIGN_ID}"

for TERRAIN in ${TERRAINS}; do
  for STYLE in ${STYLES}; do
    echo
    echo "============================================================"
    echo "[TRACER] campaign=${CAMPAIGN_ID} terrain=${TERRAIN} style=${STYLE}"
    echo "============================================================"

    TRACER_GAZEBO_RESTART_CONTAINER="${TRACER_GAZEBO_RESTART_CONTAINER:-1}" \
    TRACER_FORCE_STYLE="${STYLE}" \
    TRACER_OBJECTIVE_CONDITIONED_SELECTOR_ENABLE=0 \
    TRACER_OBJECTIVE_CONDITIONED_SELECTOR_APPLY=0 \
    TRACER_RAM_RECOVERY_SHADOW_ENABLE="${TRACER_RAM_RECOVERY_SHADOW_ENABLE:-1}" \
    TRACER_RAM_RECOVERY_ACTIVE_ENABLE="${TRACER_RAM_RECOVERY_ACTIVE_ENABLE:-1}" \
    TRACER_RAM_RECOVERY_ACTIVE_APPLY="${TRACER_RAM_RECOVERY_ACTIVE_APPLY:-1}" \
    TRACER_RAM_RECOVERY_ACTIVE_FORCE=0 \
    TRACER_ROLLOUT_TERRAINS="${TERRAIN}" \
    TRACER_ROLLOUT_REPEATS="${REPEATS}" \
    TRACER_ROLLOUT_DURATION_SEC="${DURATION}" \
    TRACER_ROLLOUT_SAMPLE_HZ="${SAMPLE_HZ}" \
    TRACER_POLICY_ID="${CAMPAIGN_ID}_${TERRAIN}_${STYLE}" \
    TRACER_META_GAIT_POLICY_KIND="${TRACER_META_GAIT_POLICY_KIND:-udp}" \
    TRACER_ENABLE_LEARNED_STACK_V3="${TRACER_ENABLE_LEARNED_STACK_V3:-1}" \
    TRACER_DEPLOY_LEARNED_STACK_V3="${TRACER_DEPLOY_LEARNED_STACK_V3:-1}" \
    TRACER_DEPLOY_LEARNED_STACK_V3_BETA_BLEND="${TRACER_DEPLOY_LEARNED_STACK_V3_BETA_BLEND:-1}" \
    TRACER_LEARNED_STACK_V3_PORT="${TRACER_LEARNED_STACK_V3_PORT:-50430}" \
    TRACER_LEARNED_STACK_V3_BETA_BLEND_ALPHA="${TRACER_LEARNED_STACK_V3_BETA_BLEND_ALPHA:-0.10}" \
    TRACER_OBJECTIVE_SELECTOR_VERBOSE="${TRACER_OBJECTIVE_SELECTOR_VERBOSE:-0}" \
    scripts/runtime/tracer_run_policy_rollout_dataset_worlds_v0.sh
  done
done

echo
echo "[TRACER] objective selector data campaign completed: ${CAMPAIGN_ID}"
